server:
  port: 8080

spring:
  application:
    name: apigateway
  data:
    redis:
      port: 6379
      host: redis
  cloud:
    gateway.server.webflux:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bookservice
          uri: lb://bookservice
          predicates:
            - Path=/api/v1/books/**
          filters:
            - name: RewritePath
              args:
                /api/v1/books/(?<segment>.*) = /${segment}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 10
                  burstCapacity: 20
                  requestedTokens: 1
            - KeyAuthFilter
        - id: employeeservice
          uri: lb://employeeservice
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 10
                  burstCapacity: 20
                  requestedTokens: 1
            - KeyAuthFilter


eureka:
  instance:
    hostname: apigateway
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discoverserver:8761/eureka